'''
created by edgard.ramos (ismytv@gmail.com)
generated by alice.bash.v.2203a
__date__
'''
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from base.libs.template import Template
from base import config as PARAMS
from base.business.bcompra import BCompra


@login_required(login_url='login')
def estadocuenta_list(request):
    url_return = 'main'
    oTemplate = Template(None)
    oTemplate.template_container = PARAMS.TemplateContainerMain
    oTemplate.template = PARAMS.Template.estadocuenta_list
    oTemplate.template_title = 'Estado Cuenta'
    oTemplate.actions['action_cancel'] = reverse(url_return)
    oTemplate.set_context()

    oBModel = BCompra()
    oTemplate.data['aPagoMes'] = oBModel.generar_cierre(request.user.license_id)

    return render(request, oTemplate.template, context=oTemplate.context)
