# Generated by Django 4.0 on 2022-04-06 22:09

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('desc', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CambioMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('monto_cambiar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('monto_cambiado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta_origen', models.IntegerField(default=0)),
                ('cuenta_destino_efectivo', models.IntegerField(default=0)),
                ('cuenta_destino_banco', models.IntegerField(default=0)),
                ('monto_deposito_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_deposito_banco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('desc', models.CharField(max_length=50)),
                ('is_servicio', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('desc', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('desc', models.CharField(max_length=50, unique=True)),
                ('destino_cuenta', models.CharField(choices=[('0', 'Efectivo'), ('1', 'Banco')], max_length=1)),
                ('tipo_cuenta', models.CharField(choices=[('0', 'Monedero'), ('1', 'Ahorro'), ('2', 'Otro')], max_length=1)),
                ('moneda', models.CharField(choices=[('0', 'Soles'), ('1', 'Dolares')], max_length=1)),
                ('numero_cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_apertura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.banco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('license_key', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(max_length=40)),
                ('num_licenses', models.IntegerField(default=3)),
                ('user_type', models.CharField(default='A', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presconcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('desc', models.CharField(max_length=50, unique=True)),
                ('monto_defecto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(choices=[('0', 'Soles'), ('1', 'Dolares')], default='0', max_length=1)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('is_tarjeta', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presrubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('desc', models.CharField(max_length=50)),
                ('tipo_movimiento', models.CharField(choices=[('0', 'Ingreso'), ('1', 'Egreso')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('desc', models.CharField(max_length=50, unique=True)),
                ('is_servicio', models.BooleanField(default=False)),
                ('tipo_movimiento', models.CharField(choices=[('0', 'Ingreso'), ('1', 'Egreso')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Rubros diario',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('desc', models.CharField(max_length=50)),
                ('dia_cierre', models.IntegerField()),
                ('portes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_pago', models.IntegerField(default=1)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.banco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('anio', models.CharField(choices=[('2022', '2022'), ('2023', '2023')], max_length=4)),
                ('mes', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(choices=[('0', 'Soles'), ('1', 'Dolares')], max_length=1)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presconcepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.presconcepto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='presconcepto',
            name='presrubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.presrubro'),
        ),
        migrations.AddField(
            model_name='presconcepto',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tarjeta'),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('id_movimiento', models.IntegerField(default=0)),
                ('tipo_movimiento', models.CharField(choices=[('0', 'Ingreso'), ('1', 'Egreso')], max_length=1)),
                ('tipo_operacion', models.CharField(choices=[('0', 'Cambio de moneda'), ('1', 'Transferencia cuentas propias'), ('2', 'Transferencia cuentas terceros'), ('3', 'Pagos varios'), ('4', 'Compras')], max_length=1)),
                ('cod_operacion', models.CharField(blank=True, max_length=10, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obs', models.CharField(blank=True, max_length=50, null=True)),
                ('cuenta_tercero', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_movimiento', models.DateField(default=datetime.datetime.now)),
                ('concepto_gasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.conceptodiario')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cuenta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='conceptodiario',
            name='rubro_diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rubrodiario'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuotas', models.IntegerField(default=1)),
                ('monto_cuota', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_compra', models.DateField()),
                ('detalle', models.CharField(blank=True, max_length=100, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('is_fuera_cierre', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('fecha_transaccion', models.DateField(blank=True, null=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.comercio')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tarjeta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('user_type', models.CharField(default='U', max_length=1, null=True)),
                ('image_file', models.ImageField(default='avatar.svg', null=True, upload_to='users/')),
                ('license_id', models.IntegerField(default=1)),
                ('status', models.CharField(default='A', max_length=1)),
                ('modo_apariencia', models.CharField(choices=[('0', 'Claro'), ('1', 'Oscuro')], default='0', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
