'''
created by edgard.ramos (ismytv@gmail.com)
generated by alice.bash.v.2203a
__date__
'''
from django import forms
from django.utils.translation import gettext_lazy as _
#from django.core.exceptions import ValidationError
from base.models import Cuenta

 
class CuentaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['desc'].widget.attrs['autofocus'] = True

    class Meta:
        model = Cuenta
        fields = [
            'desc', 'destino_cuenta', 'tipo_cuenta', 'moneda', 'banco', 
            'numero_cuenta', 'saldo_apertura'
        ]

        error_messages = {
            # 'desc': {
            #     'unique': _("Ya existe cuenta con esa descripción."),
            # },
        }

    def clean(self):
        return super().clean()
    
    def clean_desc(self):
        data = self.cleaned_data['desc'].strip().upper()
        # if Cuenta.objects.filter(desc=data).exists() :
        #     raise ValidationError("Descripción ya registrada!")

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return data