'''
created by edgard.ramos (ismytv@gmail.com)
generated by alice.bash.v.2203a
__date__
'''
from django import forms
from django.utils.translation import gettext_lazy as _
#from django.core.exceptions import ValidationError
from base.models import Presupuesto
from base.business.bpresconcepto import BPresconcepto

 
class PresupuestoForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        self.set_data()

    def set_data(self):
        oBPresconcepto = BPresconcepto()
        self.fields['presconcepto'].queryset = oBPresconcepto.get_all(self.request.user.license_id)

    class Meta:
        model = Presupuesto
        fields = ['anio', 'mes', 'presconcepto', 'monto', 'moneda', 'tipo_cambio']

        error_messages = {
            'desc': {
                'unique': _("Ya existe rubro con esa descripción."),
            },
        }

    def clean(self):
        return super().clean()
    
    # def clean_desc(self):
    #     data = self.cleaned_data['desc'].strip().upper()
    #     # if Presupuesto.objects.filter(desc=data).exists() :
    #     #     raise ValidationError("Descripción ya registrada!")

    #     # Always return a value to use as the new cleaned data, even if
    #     # this method didn't change it.
    #     return data