'''
created by edgard.ramos (ismytv@gmail.com)
generated by alice.bash.v.2203a
__date__
'''
from django import forms
from django.utils.translation import gettext_lazy as _
#from django.core.exceptions import ValidationError
from base.models import Banco

 
class BancoForm(forms.ModelForm):
    class Meta:
        model = Banco
        fields = ['desc']
        error_messages = {
            'desc': {
                'unique': _("Ya existe banco con esa descripción."),
            },
        }

    def clean(self):
        return super().clean()
    
    def clean_desc(self):
        data = self.cleaned_data['desc'].strip().upper()
        # print(data)
        # if Ubicacion_N1.objects.filter(desc=data).exists() :
        #     raise ValidationError("Descripción ya registrada!")

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return data
