'''
created by edgard.ramos (ismytv@gmail.com)
generated by alice.bash.v.2203a
__date__
'''
from django import forms
from django.utils.translation import gettext_lazy as _
#from django.core.exceptions import ValidationError
from base.models import Tarjeta, Banco

 
class TarjetaForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        self.fields['banco'].queryset = Banco.objects.filter(license_id=self.request.user.license_id).order_by('desc')
        self.fields['desc'].widget.attrs['autofocus'] = True

    class Meta:
        model = Tarjeta
        fields = ['desc', 'banco', 'dia_cierre', 'portes', 'dia_pago']

        error_messages = {
            'desc': {
                'unique': _("Ya existe rubro con esa descripción."),
            },
        }

    def clean(self):
        return super().clean()
    
    def clean_desc(self):
        data = self.cleaned_data['desc'].strip().upper()
        # if Tarjeta.objects.filter(desc=data).exists() :
        #     raise ValidationError("Descripción ya registrada!")

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return data